### ISSUE TITLE
Emoji Not Identified

### ISSUE THREAD

**Issue by philltomlinson** [kcthota/emoji4j#5]
The following emoticon does not appear to be identified correctly:

😔

U+1F614 PENSIVE FACE character

When trying to remove this using the removeAllEmojis() it is not identified.

**Comment by kcthota** [comment]
seems to be working okay. Here is the test I tried

> String text ="a fix for :pensive:";
> String emojifiedText = EmojiUtils.emojify(text);
> assertThat(EmojiUtils.removeAllEmojis(emojifiedText)).isEqualTo("a fix for ");

Do you mind sharing an unit test for the issue?

**Comment by philltomlinson** [comment]
Hi,

See here for a test I did. 
https://gist.github.com/philltomlinson/62c606e4ca61d14415324e04b2c58a94

It fails on the 4th item in the array.

**Comment by kcthota** [comment]
As per http://www.charbase.com/1f614-unicode-pensive-face, the java escape of pensive face is "\ud83d\ude14". However the character you are using in your test is \uD83D\uDE14\u000B. \u000B is the unicode character for line tabulation. 

emoji4j rightly identified \ud83d\ude14 as an emoji and removed it in following test. But the \u000B character is not removed from the string.

String text ="a fix for \uD83D\uDE14";
assertThat(EmojiUtils.removeAllEmojis(text)).isEqualTo("a fix for "); //passes
