### ISSUE TITLE
EmojiUtils.emojify() emojifies https://

### ISSUE THREAD

**Issue by Sroka** [kcthota/emoji4j#6]
As in the topic. Whenever I want to emojify text that contains some hyperlink it detects emoji in https:// Is there any way I could exclude links form emojifying? It would be perfect if there was option to emojify only emojis separated by blanks from other characters

**Comment by tterrag1098** [comment]
An option to simply skip the "emoticon" conversion entirely would be great. Seems like there would be too many edge cases like this.

**Comment by kcthota** [comment]
v6.0 now supports stopwords.

`EmojiManager.addStopWords("http://", "https://");`
